/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/x9EBEQvzvXKLaTcX/scene.splinecode')
  return (
    <>
      {/* <color attach="background" args={['#222222']} /> */}
      <group {...props} dispose={null}>
        <group name="Group" position={[-7.09, 216, 0]} rotation={[0, 0, 0.07]}>
          <mesh
            name="Cube 3"
            geometry={nodes['Cube 3'].geometry}
            material={materials['Cube 3 Material']}
            castShadow
            receiveShadow
            position={[5.8, -124.01, -262.15]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[0.18, 0.44, 1]}
          />
          <mesh
            name="Cube 4"
            geometry={nodes['Cube 4'].geometry}
            material={materials.MonitorScreen}
            castShadow
            receiveShadow
            position={[4.51, 0, 0]}
            rotation={[0, Math.PI / 2, 0]}
            scale={[16.45, 7.45, 0.38]}
          />
          <mesh
            name="Boolean 2"
            geometry={nodes['Boolean 2'].geometry}
            material={materials['Monitor ']}
            castShadow
            receiveShadow
            position={[8.56, 0, 0]}
          >
            <mesh
              name="Cube 41"
              geometry={nodes['Cube 41'].geometry}
              material={materials['Cube 41 Material']}
              visible={false}
              castShadow
              receiveShadow
              rotation={[0, Math.PI / 2, 0]}
              scale={[16.5, 7.5, 0.38]}
            />
            <mesh
              name="Cube 31"
              geometry={nodes['Cube 31'].geometry}
              material={materials['Cube 31 Material']}
              visible={false}
              castShadow
              receiveShadow
              position={[-9.05, 0, 0]}
              rotation={[0, Math.PI / 2, 0]}
              scale={[17, 8, 0.38]}
            />
          </mesh>
        </group>
        <mesh
          name="Cube 2"
          geometry={nodes['Cube 2'].geometry}
          material={materials['Monitor ']}
          castShadow
          receiveShadow
          position={[-34.69, 218.59, 0]}
          rotation={[-Math.PI / 2, Math.PI / 2, Math.PI / 2]}
          scale={[1.38, 0.49, 1]}
        />
        <mesh
          name="Boolean"
          geometry={nodes.Boolean.geometry}
          material={materials['Monitor ']}
          castShadow
          receiveShadow
          position={[-53, 153.18, 0]}
          rotation={[0, 0, -0.01]}
        >
          <mesh
            name="Cube 32"
            geometry={nodes['Cube 32'].geometry}
            material={materials['Cube 32 Material']}
            visible={false}
            castShadow
            receiveShadow
            position={[12.78, -95.2, 0]}
            rotation={[-Math.PI, 0, -0.15]}
            scale={[0.38, 0.98, 0.52]}
          />
          <mesh
            name="Cube 21"
            geometry={nodes['Cube 21'].geometry}
            material={materials['Cube 21 Material']}
            visible={false}
            castShadow
            receiveShadow
            rotation={[0, 0, 0.15]}
            scale={[0.23, 6.51, 1]}
          />
        </mesh>
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={materials['Monitor ']}
          castShadow
          receiveShadow
          scale={[1, 0.06, 1]}
        />
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.6}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          position={[200, 300, 600]}
        />
        <OrthographicCamera
          name="Personal Camera"
          makeDefault={true}
          zoom={0.5}
          far={100000}
          near={-100000}
          position={[425.43, 278.3, 625.74]}
          rotation={[-0.18, 0.46, 0.08]}
        />
        <hemisphereLight name="Default Ambient Light" intensity={1} color="#212121" position={[0, 1, 0]} />
      </group>
    </>
  )
}
