import Monitor from "./Monitor";
/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrbitControls, OrthographicCamera } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'

export const SceneWrapper = () => {
    return <Canvas>
        <OrbitControls
        makeDefault
        minAzimuthAngle={0}
        maxAzimuthAngle={Math.PI}
        minPolarAngle={Math.PI / 3}
        maxPolarAngle={Math.PI / 3}
        enableZoom={true}
        enablePan={true}
        zoomSpeed={0.3}
      />
        {/* <Scene /> */}
        <Monitor />
    </Canvas>
}

function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/4mW2UXnYybgkK9Hx/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#f3cad4']} />
      <group {...props} dispose={null}>
        <mesh
          name="BG"
          geometry={nodes.BG.geometry}
          material={materials['BG Material']}
          castShadow
          receiveShadow
          position={[900.26, -32.01, -1687.89]}
          rotation={[-Math.PI / 6, -0.75, -0.37]}
        />
        <directionalLight
          name="Directional Light"
          castShadow
          intensity={0.6}
          shadow-mapSize-width={1024}
          shadow-mapSize-height={1024}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-3610.2915}
          shadow-camera-right={3610.2915}
          shadow-camera-top={3610.2915}
          shadow-camera-bottom={-3610.2915}
          position={[-723.38, 1320.76, 435.43]}
        />
        <mesh
          name="Walls"
          geometry={nodes.Walls.geometry}
          material={materials['Walls Material']}
          castShadow
          receiveShadow
          position={[33.17, -323.76, -23.55]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={0.7}
        />
        <OrthographicCamera
                  name="Camera 2"
                  makeDefault={true}
                  zoom={0.15}
                  far={100000}
                  near={-100000}
                  position={[-3662.89, 2500.99, 3678.25]}
                  rotation={[-0.54, -0.71, -0.37]}         />
        <mesh
          name="Sphere"
          geometry={nodes.Sphere.geometry}
          material={materials['Sphere Material']}
          castShadow
          receiveShadow
          position={[-597.67, -206.69, -725.75]}
          rotation={[0, 0, -Math.PI / 2]}
        />
        <mesh
          name="book-green"
          geometry={nodes['book-green'].geometry}
          material={materials['red-6']}
          castShadow
          receiveShadow
          position={[797.82, 181.7, -733.6]}
          rotation={[-Math.PI / 2, -1.4, -Math.PI / 2]}
        />
        <mesh
          name="book-red"
          geometry={nodes['book-red'].geometry}
          material={materials['red-6']}
          castShadow
          receiveShadow
          position={[873.04, 235.86, -716.95]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="book-yellow"
          geometry={nodes['book-yellow'].geometry}
          material={materials['red-4']}
          castShadow
          receiveShadow
          position={[850.55, 201.36, -716.95]}
          rotation={[0, -Math.PI / 2, 0]}
        />
        <mesh
          name="paper"
          geometry={nodes.paper.geometry}
          material={materials['red-1']}
          castShadow
          receiveShadow
          position={[490.67, 107.27, -605.12]}
          rotation={[-Math.PI / 2, 0, -1.13]}
        />
        <group
          name="book-blue"
          position={[546.69, 122.67, -568.11]}
          rotation={[-0.01, 0.08, -1.57]}
          scale={[0.74, 1.35, 1.23]}
        >
          <mesh
            name="Rectangle"
            geometry={nodes.Rectangle.geometry}
            material={materials['red-2']}
            castShadow
            receiveShadow
            position={[-22.7, 32.77, 1.79]}
            rotation={[0, -Math.PI / 2, 0]}
          />
          <mesh
            name="Cube 4"
            geometry={nodes['Cube 4'].geometry}
            material={materials['red-1']}
            castShadow
            receiveShadow
            position={[-0.32, 0.86, 0.42]}
            scale={[0.99, 1.01, 1]}
          />
          <mesh
            name="Cube 41"
            geometry={nodes['Cube 41'].geometry}
            material={materials['Cube 41 Material']}
            castShadow
            receiveShadow
            position={[-16.68, -0.27, 9.75]}
            scale={[0.99, 1.01, 1]}
          />
        </group>
        <group name="lamp" position={[643.47, 608.8, -737.72]} scale={1.65}>
          <mesh
            name="Cylinder 4"
            geometry={nodes['Cylinder 4'].geometry}
            material={materials['Cylinder 4 Material']}
            castShadow
            receiveShadow
            position={[0.25, -105.76, -0.71]}
          />
          <mesh
            name="Cylinder 6"
            geometry={nodes['Cylinder 6'].geometry}
            material={materials['Cylinder 6 Material']}
            castShadow
            receiveShadow
            position={[-0.22, -56.91, -0.71]}
          />
          <mesh
            name="Cylinder 5"
            geometry={nodes['Cylinder 5'].geometry}
            material={materials['Cylinder 5 Material']}
            castShadow
            receiveShadow
            position={[-0.22, -155.57, -0.71]}
          />
          <mesh
            name="Cylinder 3"
            geometry={nodes['Cylinder 3'].geometry}
            material={materials['Cylinder 3 Material']}
            castShadow
            receiveShadow
            position={[-0.53, -212.52, 1.57]}
          />
          <mesh
            name="Cylinder 2"
            geometry={nodes['Cylinder 2'].geometry}
            material={materials['Cylinder 2 Material']}
            castShadow
            receiveShadow
            position={[-0.25, -296.92, 0.71]}
          />
        </group>
        <group name="Pen holder" position={[688.69, 174.4, 215.4]}>
          <mesh
            name="Cube 2"
            geometry={nodes['Cube 2'].geometry}
            material={materials['Cube 2 Material']}
            castShadow
            receiveShadow
            position={[6.44, -6.48, 8.59]}
            rotation={[0.25, -0.09, -0.25]}
          />
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials['red-1']}
            castShadow
            receiveShadow
            position={[-10.67, -17.78, -10.37]}
            rotation={[-0.17, -0.04, 0.26]}
          />
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials['UI panel-blue']}
            castShadow
            receiveShadow
            position={[-3.34, -58.97, 0]}
          />
        </group>
        <group name="artboard" position={[542.1, 165.41, -121.14]}>
          <mesh
            name="Cube 42"
            geometry={nodes['Cube 42'].geometry}
            material={materials['red-5']}
            castShadow
            receiveShadow
            position={[120.14, -9.39, -233.33]}
          />
          <mesh
            name="Cube 3"
            geometry={nodes['Cube 3'].geometry}
            material={materials['red-5']}
            castShadow
            receiveShadow
            position={[120.14, -9.39, 233.31]}
          />
          <mesh
            name="Cube 43"
            geometry={nodes['Cube 43'].geometry}
            material={materials['red-5']}
            castShadow
            receiveShadow
            position={[3.73, -4.74, -233.33]}
            rotation={[0, 0, -1.22]}
          />
          <mesh
            name="Cube 21"
            geometry={nodes['Cube 21'].geometry}
            material={materials['red-5']}
            castShadow
            receiveShadow
            position={[3.73, -4.74, 233.31]}
            rotation={[0, 0, -1.22]}
          />
          <mesh
            name="Cube 44"
            geometry={nodes['Cube 44'].geometry}
            material={materials['red-5']}
            castShadow
            receiveShadow
            position={[7.63, -63.45, -233.33]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="Cube1"
            geometry={nodes.Cube1.geometry}
            material={materials['red-5']}
            castShadow
            receiveShadow
            position={[7.63, -63.45, 233.31]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="Rectangle 2"
            geometry={nodes['Rectangle 2'].geometry}
            material={materials['Rectangle 2 Material']}
            castShadow
            receiveShadow
            position={[-3.72, 19.96, 0]}
            rotation={[-Math.PI / 2, -Math.PI / 9, -Math.PI / 2]}
          />
          <mesh
            name="Rectangle1"
            geometry={nodes.Rectangle1.geometry}
            material={materials['red-4']}
            castShadow
            receiveShadow
            position={[3.42, 0.36, 0]}
            rotation={[-Math.PI / 2, -Math.PI / 9, -Math.PI / 2]}
          />
        </group>
        <group name="picture-2" position={[320.04, -166.06, -715.26]} rotation={[-0.09, 0, 0]}>
          <mesh
            name="Rectangle2"
            geometry={nodes.Rectangle2.geometry}
            material={materials['red-6']}
            castShadow
            receiveShadow
            position={[-0.56, -0.28, 12.36]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="Cube2"
            geometry={nodes.Cube2.geometry}
            material={materials['red-5']}
            castShadow
            receiveShadow
            position={[0, 0, -0.36]}
          />
        </group>
        <group name="window" position={[129, 617.5, -853.89]}>
          <mesh
            name="Cube 45"
            geometry={nodes['Cube 45'].geometry}
            material={materials['red-4']}
            castShadow
            receiveShadow
            position={[0.63, 0.94, -10.81]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="Cube 5"
            geometry={nodes['Cube 5'].geometry}
            material={materials['red-4']}
            castShadow
            receiveShadow
            position={[1.69, 105.58, 0]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh
            name="窗户"
            geometry={nodes.窗户.geometry}
            material={materials['窗户 Material']}
            castShadow
            receiveShadow
            position={[0, 0, 9.16]}
            rotation={[0, 0, -Math.PI / 2]}
          />
        </group>
        <group name="plant" position={[455.43, 55.44, 698.46]} rotation={[0, 0.4, 0]} scale={0.75}>
          <mesh
            name="Cube 22"
            geometry={nodes['Cube 22'].geometry}
            material={materials['plant-green']}
            castShadow
            receiveShadow
            position={[15.33, 90.95, -1.22]}
            rotation={[0, Math.PI / 4, 0]}
          />
          <mesh
            name="Cube 31"
            geometry={nodes['Cube 31'].geometry}
            material={materials['plant-green']}
            castShadow
            receiveShadow
            position={[-21.33, 13.1, 36.98]}
            rotation={[-3.05, -Math.PI / 4, -3.05]}
            scale={1.05}
          />
          <mesh
            name="Cube 46"
            geometry={nodes['Cube 46'].geometry}
            material={materials['plant-green']}
            castShadow
            receiveShadow
            position={[41.41, -15.63, -119.81]}
            rotation={[-0.04, 1.22, -0.22]}
          />
          <mesh
            name="Cube 51"
            geometry={nodes['Cube 51'].geometry}
            material={materials['plant-green']}
            castShadow
            receiveShadow
            position={[-12.89, -31.14, 51.83]}
            rotation={[-3.11, 1.3, -2.91]}
            scale={1.05}
          />
          <mesh
            name="Cube3"
            geometry={nodes.Cube3.geometry}
            material={materials['plant-green']}
            castShadow
            receiveShadow
            position={[17.45, -42.1, 91.53]}
            rotation={[0, -1.22, -0.17]}
          />
          <mesh
            name="Ellipse 3"
            geometry={nodes['Ellipse 3'].geometry}
            material={materials['red-5']}
            castShadow
            receiveShadow
            position={[7.85, -163.99, 1.2]}
            rotation={[-Math.PI / 2, 0, -1.98]}
            scale={1.33}
          />
          <mesh
            name="Plant Base"
            geometry={nodes['Plant Base'].geometry}
            material={materials['Plant Base Material']}
            castShadow
            receiveShadow
            position={[13.95, -366.41, 0.56]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.44}
          />
        </group>
        <group name="table" position={[868.04, -467.73, -369.18]}>
          <mesh
            name="Cylinder 31"
            geometry={nodes['Cylinder 31'].geometry}
            material={materials['table-ao']}
            castShadow
            receiveShadow
            position={[262.37, -38.32, -709.39]}
          />
          <mesh
            name="Cylinder 21"
            geometry={nodes['Cylinder 21'].geometry}
            material={materials['table-ao']}
            castShadow
            receiveShadow
            position={[262.37, -38.32, 862.8]}
          />
          <mesh
            name="Cylinder 32"
            geometry={nodes['Cylinder 32'].geometry}
            material={materials['table-ao']}
            castShadow
            receiveShadow
            position={[-249.05, -35.67, -709.39]}
          />
          <mesh
            name="Cylinder1"
            geometry={nodes.Cylinder1.geometry}
            material={materials['table-ao']}
            castShadow
            receiveShadow
            position={[-249.05, -38.32, 862.8]}
          />
          <mesh
            name="Rectangle3"
            geometry={nodes.Rectangle3.geometry}
            material={materials['Rectangle3 Material']}
            castShadow
            receiveShadow
            position={[0, 230.16, 91.5]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
        </group>
        <group name="carpet" position={[-177.84, -318.39, 98.4]}>
          <mesh
            name="Ellipse 2"
            geometry={nodes['Ellipse 2'].geometry}
            material={materials['Ellipse 2 Material']}
            castShadow
            receiveShadow
            position={[0, 7.39, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1.09, 1.09, 1.66]}
          />
          <mesh
            name="Ellipse"
            geometry={nodes.Ellipse.geometry}
            material={materials['Ellipse Material']}
            castShadow
            receiveShadow
            position={[0, -7.39, 0]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={[1.09, 1.09, 1.66]}
          />
        </group>
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" position={[0, 1, 0]} />
      </group>
    </>
  )
}
